#pragma once

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1

#define AZOTEQ_IQS5XX_TPS43 1
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
#define AZOTEQ_IQS5XX_HOLD_TIME 100
#define AZOTEQ_IQS5XX_SCROLL_INITIAL_DISTANCE 10